// <auto-generated />
using System;
using FormReporting.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormReporting.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251106160147_InitialCreate_Sections1And2_OrganizationalAndIdentity")]
    partial class InitialCreate_Sections1And2_OrganizationalAndIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FormReporting.Models.Entities.Identity.MenuItem", b =>
                {
                    b.Property<int>("MenuItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuItemId"));

                    b.Property<string>("Action")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Area")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Controller")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("MenuCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MenuTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("ModuleId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentMenuItemId")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresAuth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Route")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MenuItemId");

                    b.HasIndex("DisplayOrder")
                        .HasDatabaseName("IX_MenuItem_Order");

                    b.HasIndex("MenuCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_MenuItem_Code");

                    b.HasIndex("ModuleId")
                        .HasDatabaseName("IX_MenuItem_Module");

                    b.HasIndex("IsActive", "IsVisible")
                        .HasDatabaseName("IX_MenuItem_Active");

                    b.HasIndex("ParentMenuItemId", "DisplayOrder")
                        .HasDatabaseName("IX_MenuItem_Parent");

                    b.ToTable("MenuItems", (string)null);
                });

            modelBuilder.Entity("FormReporting.Models.Entities.Identity.Module", b =>
                {
                    b.Property<int>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModuleId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ModuleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ModuleId");

                    b.HasIndex("ModuleCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Modules_Code");

                    b.HasIndex("ModuleName")
                        .IsUnique()
                        .HasDatabaseName("UQ_Module_Name");

                    b.HasIndex("IsActive", "DisplayOrder")
                        .HasDatabaseName("IX_Modules_Active");

                    b.ToTable("Modules", (string)null);
                });

            modelBuilder.Entity("FormReporting.Models.Entities.Identity.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PermissionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PermissionId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Permission_Active");

                    b.HasIndex("PermissionCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Permission_Code");

                    b.HasIndex("ModuleId", "IsActive")
                        .HasDatabaseName("IX_Permission_Module");

                    b.HasIndex("ModuleId", "PermissionCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_Permission_Module");

                    b.HasIndex("PermissionType", "IsActive")
                        .HasDatabaseName("IX_Permission_Type");

                    b.ToTable("Permissions", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Permission_Type", "PermissionType IN ('View', 'Create', 'Edit', 'Delete', 'Approve', 'Export', 'Manage', 'Custom')");
                        });
                });

            modelBuilder.Entity("FormReporting.Models.Entities.Identity.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_Role_Code");

                    b.HasIndex("RoleName")
                        .IsUnique()
                        .HasDatabaseName("UQ_Role_Name");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("FormReporting.Models.Entities.Identity.RoleMenuItem", b =>
                {
                    b.Property<int>("RoleMenuItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleMenuItemId"));

                    b.Property<DateTime>("AssignedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("RoleMenuItemId");

                    b.HasIndex("MenuItemId")
                        .HasDatabaseName("IX_RoleMenuItem_MenuItem");

                    b.HasIndex("RoleId", "IsVisible")
                        .HasDatabaseName("IX_RoleMenuItem_Role");

                    b.HasIndex("RoleId", "MenuItemId")
                        .IsUnique()
                        .HasDatabaseName("UQ_RoleMenuItem");

                    b.ToTable("RoleMenuItems", (string)null);
                });

            modelBuilder.Entity("FormReporting.Models.Entities.Identity.RolePermission", b =>
                {
                    b.Property<int>("RolePermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolePermissionId"));

                    b.Property<int?>("AssignedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsGranted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("RolePermissionId");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("IX_RolePermission_Permission");

                    b.HasIndex("RoleId", "IsGranted")
                        .HasDatabaseName("IX_RolePermission_Role");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique()
                        .HasDatabaseName("UQ_RolePermission");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("FormReporting.Models.Entities.Identity.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("AccessFailedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("EmployeeNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("UserId");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("IX_User_Department");

                    b.HasIndex("EmployeeNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_User_EmployeeNumber")
                        .HasFilter("EmployeeNumber IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("NormalizedUserName")
                        .HasDatabaseName("IX_Users_Username");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("UQ_User_UserName");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("FormReporting.Models.Entities.Identity.UserGroup", b =>
                {
                    b.Property<int>("UserGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserGroupId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GroupCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GroupType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("UserGroupId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("GroupCode")
                        .IsUnique()
                        .HasDatabaseName("IX_UserGroup_Code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_UserGroup_Active");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_UserGroup_Tenant");

                    b.ToTable("UserGroups", (string)null);
                });

            modelBuilder.Entity("FormReporting.Models.Entities.Identity.UserGroupMember", b =>
                {
                    b.Property<int>("UserGroupMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserGroupMemberId"));

                    b.Property<int>("AddedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("UserGroupId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserGroupMemberId");

                    b.HasIndex("AddedBy");

                    b.HasIndex("UserGroupId")
                        .HasDatabaseName("IX_UserGroupMember_Group");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserGroupMember_User");

                    b.HasIndex("UserGroupId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("UQ_UserGroupMember_Group_User");

                    b.ToTable("UserGroupMembers", (string)null);
                });

            modelBuilder.Entity("FormReporting.Models.Entities.Identity.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRoleId"));

                    b.Property<int?>("AssignedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserRoleId");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_UserRoles_Role");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserRoles_User");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("UQ_UserRole");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("FormReporting.Models.Entities.Identity.UserTenantAccess", b =>
                {
                    b.Property<int>("AccessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccessId"));

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GrantedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("GrantedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AccessId");

                    b.HasIndex("ExpiryDate")
                        .HasDatabaseName("IX_UserTenantAccess_Expiry")
                        .HasFilter("ExpiryDate IS NOT NULL AND IsActive = 1");

                    b.HasIndex("GrantedBy");

                    b.HasIndex("TenantId", "IsActive")
                        .HasDatabaseName("IX_UserTenantAccess_Tenant");

                    b.HasIndex("UserId", "IsActive")
                        .HasDatabaseName("IX_UserTenantAccess_User");

                    b.HasIndex("UserId", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("UQ_UserTenant");

                    b.ToTable("UserTenantAccess", (string)null);
                });

            modelBuilder.Entity("FormReporting.Models.Entities.Organizational.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("ParentDepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("DepartmentId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Department_Active");

                    b.HasIndex("ParentDepartmentId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Department_Tenant");

                    b.HasIndex("TenantId", "DepartmentCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_Department_Tenant_Code");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("FormReporting.Models.Entities.Organizational.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegionId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("RegionCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RegionNumber")
                        .HasColumnType("int");

                    b.Property<int?>("RegionalManagerUserId")
                        .HasColumnType("int");

                    b.HasKey("RegionId");

                    b.HasIndex("RegionCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_Region_Code");

                    b.HasIndex("RegionNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_Region_Number");

                    b.HasIndex("RegionalManagerUserId");

                    b.ToTable("Regions", (string)null);
                });

            modelBuilder.Entity("FormReporting.Models.Entities.Organizational.Tenant", b =>
                {
                    b.Property<int>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TenantId"));

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("ICTSupportUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10, 7)");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(10, 7)");

                    b.Property<int?>("ManagerUserId")
                        .HasColumnType("int");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int");

                    b.Property<string>("TenantCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenantType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TenantId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ICTSupportUserId");

                    b.HasIndex("ManagerUserId");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("TenantCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Tenants_Code");

                    b.HasIndex("IsActive", "TenantType")
                        .HasDatabaseName("IX_Tenants_Active");

                    b.HasIndex("RegionId", "IsActive")
                        .HasDatabaseName("IX_Tenants_Region")
                        .HasFilter("TenantType = 'Factory'");

                    b.HasIndex("TenantType", "IsActive")
                        .HasDatabaseName("IX_Tenants_Type");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("TenantType", "IsActive"), new[] { "TenantName" });

                    b.ToTable("Tenants", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Tenant_Region", "(TenantType = 'Factory' AND RegionId IS NOT NULL) OR (TenantType IN ('HeadOffice', 'Subsidiary') AND RegionId IS NULL)");

                            t.HasCheckConstraint("CHK_Tenant_Type", "TenantType IN ('HeadOffice', 'Factory', 'Subsidiary')");
                        });
                });

            modelBuilder.Entity("FormReporting.Models.Entities.Organizational.TenantGroup", b =>
                {
                    b.Property<int>("TenantGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TenantGroupId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GroupCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("TenantGroupId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("GroupCode")
                        .IsUnique()
                        .HasDatabaseName("IX_TenantGroups_Code");

                    b.HasIndex("GroupName")
                        .IsUnique()
                        .HasDatabaseName("UQ_TenantGroup_Name");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_TenantGroups_Active");

                    b.ToTable("TenantGroups", (string)null);
                });

            modelBuilder.Entity("FormReporting.Models.Entities.Organizational.TenantGroupMember", b =>
                {
                    b.Property<int>("GroupMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupMemberId"));

                    b.Property<int>("AddedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("TenantGroupId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("GroupMemberId");

                    b.HasIndex("AddedBy");

                    b.HasIndex("TenantGroupId")
                        .HasDatabaseName("IX_GroupMembers_Group");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_GroupMembers_Tenant");

                    b.HasIndex("TenantGroupId", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("UQ_GroupMember_Group_Tenant");

                    b.ToTable("TenantGroupMembers", (string)null);
                });

            modelBuilder.Entity("FormReporting.Models.Entities.Identity.MenuItem", b =>
                {
                    b.HasOne("FormReporting.Models.Entities.Identity.Module", "Module")
                        .WithMany("MenuItems")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_MenuItem_Module");

                    b.HasOne("FormReporting.Models.Entities.Identity.MenuItem", "ParentMenuItem")
                        .WithMany("ChildMenuItems")
                        .HasForeignKey("ParentMenuItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_MenuItem_Parent");

                    b.Navigation("Module");

                    b.Navigation("ParentMenuItem");
                });

            modelBuilder.Entity("FormReporting.Models.Entities.Identity.Permission", b =>
                {
                    b.HasOne("FormReporting.Models.Entities.Identity.Module", "Module")
                        .WithMany("Permissions")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Permission_Module");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("FormReporting.Models.Entities.Identity.RoleMenuItem", b =>
                {
                    b.HasOne("FormReporting.Models.Entities.Identity.MenuItem", "MenuItem")
                        .WithMany("RoleMenuItems")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RoleMenuItem_MenuItem");

                    b.HasOne("FormReporting.Models.Entities.Identity.Role", "Role")
                        .WithMany("RoleMenuItems")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RoleMenuItem_Role");

                    b.Navigation("MenuItem");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FormReporting.Models.Entities.Identity.RolePermission", b =>
                {
                    b.HasOne("FormReporting.Models.Entities.Identity.User", "Assigner")
                        .WithMany()
                        .HasForeignKey("AssignedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_RolePermission_AssignedBy");

                    b.HasOne("FormReporting.Models.Entities.Identity.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RolePermission_Permission");

                    b.HasOne("FormReporting.Models.Entities.Identity.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RolePermission_Role");

                    b.Navigation("Assigner");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FormReporting.Models.Entities.Identity.User", b =>
                {
                    b.HasOne("FormReporting.Models.Entities.Organizational.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_User_Department");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("FormReporting.Models.Entities.Identity.UserGroup", b =>
                {
                    b.HasOne("FormReporting.Models.Entities.Identity.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_UserGroup_Creator");

                    b.HasOne("FormReporting.Models.Entities.Organizational.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_UserGroup_Tenant");

                    b.Navigation("Creator");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("FormReporting.Models.Entities.Identity.UserGroupMember", b =>
                {
                    b.HasOne("FormReporting.Models.Entities.Identity.User", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_UserGroupMember_AddedBy");

                    b.HasOne("FormReporting.Models.Entities.Identity.UserGroup", "UserGroup")
                        .WithMany("Members")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserGroupMember_Group");

                    b.HasOne("FormReporting.Models.Entities.Identity.User", "User")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserGroupMember_User");

                    b.Navigation("AddedByUser");

                    b.Navigation("User");

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("FormReporting.Models.Entities.Identity.UserRole", b =>
                {
                    b.HasOne("FormReporting.Models.Entities.Identity.User", "Assigner")
                        .WithMany()
                        .HasForeignKey("AssignedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FormReporting.Models.Entities.Identity.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserRole_Role");

                    b.HasOne("FormReporting.Models.Entities.Identity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserRole_User");

                    b.Navigation("Assigner");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FormReporting.Models.Entities.Identity.UserTenantAccess", b =>
                {
                    b.HasOne("FormReporting.Models.Entities.Identity.User", "Grantor")
                        .WithMany()
                        .HasForeignKey("GrantedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_UserAccess_GrantedBy");

                    b.HasOne("FormReporting.Models.Entities.Organizational.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_UserAccess_Tenant");

                    b.HasOne("FormReporting.Models.Entities.Identity.User", "User")
                        .WithMany("TenantAccesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_UserAccess_User");

                    b.Navigation("Grantor");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FormReporting.Models.Entities.Organizational.Department", b =>
                {
                    b.HasOne("FormReporting.Models.Entities.Organizational.Department", "ParentDepartment")
                        .WithMany("ChildDepartments")
                        .HasForeignKey("ParentDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Department_Parent");

                    b.HasOne("FormReporting.Models.Entities.Organizational.Tenant", "Tenant")
                        .WithMany("Departments")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Department_Tenant");

                    b.Navigation("ParentDepartment");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("FormReporting.Models.Entities.Organizational.Region", b =>
                {
                    b.HasOne("FormReporting.Models.Entities.Identity.User", "RegionalManager")
                        .WithMany()
                        .HasForeignKey("RegionalManagerUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("RegionalManager");
                });

            modelBuilder.Entity("FormReporting.Models.Entities.Organizational.Tenant", b =>
                {
                    b.HasOne("FormReporting.Models.Entities.Identity.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Tenant_Creator");

                    b.HasOne("FormReporting.Models.Entities.Identity.User", "ICTSupport")
                        .WithMany()
                        .HasForeignKey("ICTSupportUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FormReporting.Models.Entities.Identity.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FormReporting.Models.Entities.Identity.User", "Modifier")
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Tenant_Modifier");

                    b.HasOne("FormReporting.Models.Entities.Organizational.Region", "Region")
                        .WithMany("Tenants")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Tenant_Region");

                    b.Navigation("Creator");

                    b.Navigation("ICTSupport");

                    b.Navigation("Manager");

                    b.Navigation("Modifier");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("FormReporting.Models.Entities.Organizational.TenantGroup", b =>
                {
                    b.HasOne("FormReporting.Models.Entities.Identity.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_TenantGroup_Creator");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("FormReporting.Models.Entities.Organizational.TenantGroupMember", b =>
                {
                    b.HasOne("FormReporting.Models.Entities.Identity.User", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_GroupMember_AddedBy");

                    b.HasOne("FormReporting.Models.Entities.Organizational.TenantGroup", "TenantGroup")
                        .WithMany("Members")
                        .HasForeignKey("TenantGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GroupMember_Group");

                    b.HasOne("FormReporting.Models.Entities.Organizational.Tenant", "Tenant")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GroupMember_Tenant");

                    b.Navigation("AddedByUser");

                    b.Navigation("Tenant");

                    b.Navigation("TenantGroup");
                });

            modelBuilder.Entity("FormReporting.Models.Entities.Identity.MenuItem", b =>
                {
                    b.Navigation("ChildMenuItems");

                    b.Navigation("RoleMenuItems");
                });

            modelBuilder.Entity("FormReporting.Models.Entities.Identity.Module", b =>
                {
                    b.Navigation("MenuItems");

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("FormReporting.Models.Entities.Identity.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("FormReporting.Models.Entities.Identity.Role", b =>
                {
                    b.Navigation("RoleMenuItems");

                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("FormReporting.Models.Entities.Identity.User", b =>
                {
                    b.Navigation("GroupMemberships");

                    b.Navigation("TenantAccesses");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("FormReporting.Models.Entities.Identity.UserGroup", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("FormReporting.Models.Entities.Organizational.Department", b =>
                {
                    b.Navigation("ChildDepartments");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("FormReporting.Models.Entities.Organizational.Region", b =>
                {
                    b.Navigation("Tenants");
                });

            modelBuilder.Entity("FormReporting.Models.Entities.Organizational.Tenant", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("GroupMemberships");
                });

            modelBuilder.Entity("FormReporting.Models.Entities.Organizational.TenantGroup", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
