using FormReporting.Models.ViewModels.Components;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FormReporting.Extensions
{
    /// <summary>
    /// Extension methods for building breadcrumbs from configuration or route data
    /// Handles all transformation logic - Views only provide data, Extensions build the structure
    /// Follows three-layer pattern: Config → Extension → ViewModel
    /// </summary>
    public static class BreadcrumbExtensions
    {
        /// <summary>
        /// Transforms BreadcrumbConfig into BreadcrumbViewModel
        /// If no items provided, auto-generates from route data
        /// ALL logic happens here - partials receive fully prepared data with ZERO logic needed
        /// </summary>
        public static BreadcrumbViewModel BuildBreadcrumb(
            this BreadcrumbConfig config,
            ViewContext viewContext)
        {
            // 1. Get page title
            var pageTitle = config.PageTitle
                ?? viewContext.ViewData["Title"]?.ToString()
                ?? "Dashboard";

            // 2. Build items (custom or auto-generated)
            var items = config.Items.Any()
                ? BuildCustomItems(config)
                : BuildAutoGeneratedItems(config, viewContext);

            // 3. Build view model
            return new BreadcrumbViewModel
            {
                PageTitle = pageTitle,
                Items = items
            };
        }

        /// <summary>
        /// Auto-generates breadcrumb from route data (controller, action)
        /// </summary>
        public static BreadcrumbViewModel BuildBreadcrumbFromRoute(ViewContext viewContext)
        {
            var config = new BreadcrumbConfig
            {
                ShowHomeLink = true,
                Items = new List<BreadcrumbItem>()
            };

            return config.BuildBreadcrumb(viewContext);
        }

        // ========== Fluent API Methods ==========

        /// <summary>
        /// Set page title
        /// </summary>
        public static BreadcrumbConfig WithPageTitle(this BreadcrumbConfig config, string title)
        {
            config.PageTitle = title;
            return config;
        }

        /// <summary>
        /// Add a breadcrumb item
        /// </summary>
        public static BreadcrumbConfig WithItem(this BreadcrumbConfig config,
            string title,
            string? url = null)
        {
            config.Items.Add(new BreadcrumbItem
            {
                Title = title,
                Url = url,
                DisplayOrder = config.Items.Count + 1
            });
            return config;
        }

        /// <summary>
        /// Add home link
        /// </summary>
        public static BreadcrumbConfig WithHome(this BreadcrumbConfig config,
            string text = "Home",
            string? url = null)
        {
            config.ShowHomeLink = true;
            config.HomeLinkText = text;
            config.HomeLinkUrl = url;
            return config;
        }

        /// <summary>
        /// Disable home link
        /// </summary>
        public static BreadcrumbConfig WithoutHome(this BreadcrumbConfig config)
        {
            config.ShowHomeLink = false;
            return config;
        }

        // ========== Helper Methods (For Extension Use Only - NOT for Views) ==========

        /// <summary>
        /// Build breadcrumb items from custom configuration
        /// </summary>
        private static List<BreadcrumbItemViewModel> BuildCustomItems(BreadcrumbConfig config)
        {
            var result = new List<BreadcrumbItemViewModel>();

            // Add home link if enabled
            if (config.ShowHomeLink)
            {
                result.Add(new BreadcrumbItemViewModel
                {
                    Title = config.HomeLinkText,
                    Url = config.HomeLinkUrl ?? "/",
                    CssClasses = "breadcrumb-item",
                    DisplayOrder = 0
                });
            }

            // Add custom items
            var orderedItems = config.Items.OrderBy(i => i.DisplayOrder).ToList();
            foreach (var item in orderedItems)
            {
                result.Add(new BreadcrumbItemViewModel
                {
                    Title = item.Title,
                    Url = item.Url,
                    CssClasses = string.IsNullOrEmpty(item.Url)
                        ? "breadcrumb-item active"
                        : "breadcrumb-item",
                    DisplayOrder = item.DisplayOrder
                });
            }

            return result;
        }

        /// <summary>
        /// Auto-generate breadcrumb items from route data
        /// </summary>
        private static List<BreadcrumbItemViewModel> BuildAutoGeneratedItems(
            BreadcrumbConfig config,
            ViewContext viewContext)
        {
            var result = new List<BreadcrumbItemViewModel>();
            var routeData = viewContext.RouteData.Values;

            var controller = routeData["controller"]?.ToString();
            var action = routeData["action"]?.ToString();
            var area = routeData["area"]?.ToString();

            int order = 0;

            // 1. Add Home link
            if (config.ShowHomeLink)
            {
                result.Add(new BreadcrumbItemViewModel
                {
                    Title = config.HomeLinkText,
                    Url = config.HomeLinkUrl ?? "/",
                    CssClasses = "breadcrumb-item",
                    DisplayOrder = order++
                });
            }

            // 2. Add Area (if exists)
            if (!string.IsNullOrEmpty(area) && area.ToLower() != "home")
            {
                result.Add(new BreadcrumbItemViewModel
                {
                    Title = SplitCamelCase(area),
                    Url = null, // Areas don't have direct URLs
                    CssClasses = "breadcrumb-item",
                    DisplayOrder = order++
                });
            }

            // 3. Add Controller (if not Home and not the final item)
            if (!string.IsNullOrEmpty(controller) && controller.ToLower() != "home")
            {
                var controllerTitle = SplitCamelCase(controller);

                // Only make it a link if we're not on the Index action
                var controllerUrl = (action?.ToLower() == "index")
                    ? null
                    : $"/{controller}";

                result.Add(new BreadcrumbItemViewModel
                {
                    Title = controllerTitle,
                    Url = controllerUrl,
                    CssClasses = controllerUrl == null
                        ? "breadcrumb-item active"
                        : "breadcrumb-item",
                    DisplayOrder = order++
                });
            }

            // 4. Add Action (if not Index)
            if (!string.IsNullOrEmpty(action) && action.ToLower() != "index")
            {
                result.Add(new BreadcrumbItemViewModel
                {
                    Title = SplitCamelCase(action),
                    Url = null, // Current page is always active
                    CssClasses = "breadcrumb-item active",
                    DisplayOrder = order++
                });
            }

            return result;
        }

        /// <summary>
        /// Convert CamelCase to separate words
        /// Examples: "RegionDetails" -> "Region Details", "CreateNew" -> "Create New"
        /// </summary>
        private static string SplitCamelCase(string input)
        {
            if (string.IsNullOrEmpty(input))
                return input;

            // Insert space before uppercase letters (except the first one)
            var result = System.Text.RegularExpressions.Regex.Replace(
                input,
                "([A-Z])",
                " $1",
                System.Text.RegularExpressions.RegexOptions.Compiled
            ).Trim();

            return result;
        }

        /// <summary>
        /// Get friendly name for controller
        /// Can be extended to use a dictionary for custom mappings
        /// </summary>
        private static string GetFriendlyControllerName(string controller)
        {
            // Add custom mappings here if needed
            var mappings = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                { "Regions", "Regions" },
                { "Tenants", "Tenants" },
                { "Users", "Users" },
                { "Roles", "Roles" },
                { "Dashboard", "Dashboard" }
            };

            return mappings.ContainsKey(controller)
                ? mappings[controller]
                : SplitCamelCase(controller);
        }

        /// <summary>
        /// Get friendly name for action
        /// Can be extended to use a dictionary for custom mappings
        /// </summary>
        private static string GetFriendlyActionName(string action)
        {
            // Add custom mappings here if needed
            var mappings = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                { "Index", "List" },
                { "Details", "Details" },
                { "Create", "Create New" },
                { "Edit", "Edit" },
                { "Delete", "Delete" }
            };

            return mappings.ContainsKey(action)
                ? mappings[action]
                : SplitCamelCase(action);
        }
    }
}
